version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5433"  # Host port 5433 maps to container port 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lolbro78

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"  # Host port 8080 maps to Adminer container's port 8080

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"  # Host port 6379 maps to container port 6379
    volumes:
      - ./data/redis:/data  # Persistent storage for Redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]  # Optional: Custom Redis config
