version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Changed the host port to 5433
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lolbro78

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
